name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: port19x
          template: classic
          base: activity, community
          base_indepth: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_rss: yes
          plugin_rss_limit: 1
          plugin_rss_source: https://port19.xyz/rss.xml
