name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: port19x
          template: classic
          base: activity, community
          base_indepth: yes
          config_timezone: Europe/Berlin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: javascript
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
      - uses: lowlighter/metrics@latest
        with:
          filename: ani-cli.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          user: pystardust
          repo: ani-cli
          plugin_lines: yes
          plugin_followup: yes
          plugin_people: yes
          plugin_people_limit: 8
          plugin_people_types: contributors, thanks
          plugin_people_thanks: justfoolingaround, koalaman
          plugin_traffic: yes
      - uses: lowlighter/metrics@latest
        with:
          filename: website-metrics.svg
          user: port19x
          template: classic
          base: ""
          config_timezone: Europe/Berlin
          plugin_pagespeed: yes
          plugin_pagespeed_url: port19.xyz
          plugin_rss: yes
          plugin_rss_limit: 1
          plugin_rss_source: https://port19.xyz/rss.xml
