name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: ani-cli.svg
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          user: pystardust
          repo: ani-cli
          plugin_followup: yes
          plugin_contributors: yes
          plugin_contributors_categories: |
            {
            "Code": ["ani-cli"],
            "Quality": [".github/**"],
            "Documentation": ["README.md", "ani-cli.1.gz", ".assets/**"],
            "Governance": ["CONTRIBUTING.md", "LICENSE", "disclaimer.md"],
            "#️Others": ["*"]
            }
          plugin_traffic: yes
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community
          base_indepth: yes
